# Generated by Django 6.0 on 2026-02-28 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userstrava'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstrava',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='strava', to='users.user'),
            preserve_default=False,
        ),
    ]
