# Generated by Django 6.0 on 2026-02-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userstrava_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstrava',
            name='scope',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
