# Generated by Django 6.0 on 2026-02-28 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userstrava_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFitnessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_vam', models.FloatField()),
                ('fitness_tier', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('elite', 'Elite')], max_length=20)),
                ('rides_analyzed', models.PositiveIntegerField()),
                ('last_synced_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_profile', to='users.user')),
            ],
        ),
    ]
