# Generated by Django 6.0 on 2026-03-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_geocodedlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('radius', models.IntegerField()),
                ('vote', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
