# Generated by Django 6.0 on 2026-03-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_searchfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchfeedback',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchfeedback',
            name='vote',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
