# Generated by Django 6.0 on 2026-03-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_add_comment_nullable_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
